# Configuração para forçar o ambiente de build da Railway (Nixpacks)
[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.curl",
    "php82Extensions.intl",
    "php82Extensions.libxml",
    "php82Extensions.simplexml",
    "php82Extensions.zip",
    "php82Extensions.pdo_mysql"
]